Update README.md
loadimpact/postman-to-loadimpact pull request #6
Opened 2020-01-22 12:12 UTC by simskij

2020-02-02 18:01 UTC, robingustafsson requested changes
Just a small change and then we can merge.

2020-02-02 18:01 UTC, robingustafsson commented on README.md
> +> This tool has been deprecated in favor of [postman to k2](https://github.com/loadimpact/postman-to-k2).
@simskij "k2" -> "k6" 😄

2020-02-02 18:02 UTC, simskij commented on README.md
> +> This tool has been deprecated in favor of [postman to k2](https://github.com/loadimpact/postman-to-k2).
Hahaha will fix 😂

2020-02-03 13:53 UTC, robingustafsson approved these changes

2021-11-11 13:13 UTC, closed without merging